package templates

import (
	"bytes"
	"fmt"
	"github.com/dengpju/higo-utils/utils"
	"go/ast"
	"go/build"
	"go/format"
	"go/parser"
	"go/token"
	"io"
	"io/ioutil"
	"log"
	"os"
	"runtime"
	"strings"
	"text/template"
	"github.com/pkg/errors"
	"github.com/win5do/go-lib/errx"
)

type Controller struct {
	Package string
	Name    string
	File    string
}

func NewController(pkg string, name string, file string) *Controller {
	name = utils.Ucfirst(name)
	name = name + controller
	file = file + utils.PathSeparator() + strings.Trim(name, controller) + controller + ".go"
	return &Controller{Package: pkg, Name: name, File: file}
}

func (this *Controller) Template() string {
	_, file, _, _ := runtime.Caller(0)
	file = strings.TrimRight(file, ".go") + ".tpl"
	f, err := os.Open(file)
	if err != nil {
		panic(err)
	}
	context, err := ioutil.ReadAll(f)
	if err != nil {
		panic(err)
	}
	return string(context)
}

func (this *Controller) Generate() {
	_, mainfile, _, _ := runtime.Caller(3)
	fmt.Println(mainfile)
	app := strings.Trim(mainfile, "main.go") + ".." + utils.PathSeparator() + "app"
	fmt.Println(app)
	autoload := app + utils.PathSeparator() + "Beans" + utils.PathSeparator() + "autoload"
	fmt.Println(autoload)
	pkg, _ := run(autoload, "autoload")

	fi, err := os.OpenFile(this.File, os.O_RDWR|os.O_CREATE, 0755)
	if err != nil {
		panic(err)
	}
	defer fi.Close()

	tpl := this.Template()
	tmpl, err := template.New(controller).Parse(tpl)
	if err != nil {
		panic(err)
	}
	err = tmpl.Execute(fi, this)
	if err != nil {
		panic(err)
	}
	fmt.Println(os.Getwd())
	log.Println("package name: ", this.Package)
	log.Println("controller name: ", this.Name)
	log.Println("output file: ", this.File)
}

func run(dir string, pkgName string) error {
	/**
	dir, err := getImportPkg("go.uber.org/zap")
	if err != nil {
		return errx.WithStackOnce(err)
	}
	log.Printf("dir: %+v", dir)
	 */

	pkg, err := parseDir(dir, pkgName)
	if err != nil {
		return errx.WithStackOnce(err)
	}
	funcs, err := walkAst(pkg)
	if err != nil {
		return errx.WithStackOnce(err)
	}
	err = writeGoFile(os.Stdout, funcs)
	if err != nil {
		return errx.WithStackOnce(err)
	}
	return nil
}

func getImportPkg(pkg string) (string, error) {
	p, err := build.Import(pkg, "", build.FindOnly)
	if err != nil {
		return "", err
	}
	return p.Dir, err
}

func parseDir(dir, pkgName string) (*ast.Package, error) {
	pkgMap, err := parser.ParseDir(
		token.NewFileSet(),
		dir,
		func(info os.FileInfo) bool {
			// skip go-test
			return !strings.Contains(info.Name(), "_test.go")
		},
		parser.Mode(0), // no comment
	)
	if err != nil {
		return nil, errx.WithStackOnce(err)
	}
	pkg, ok := pkgMap[pkgName]
	if !ok {
		err := errors.New("not found")
		return nil, errx.WithStackOnce(err)
	}
	return pkg, nil
}

type visitor struct {
	funcs []*ast.FuncDecl
}

func (v *visitor) Visit(node ast.Node) ast.Visitor {
	switch n := node.(type) {
	case *ast.FuncDecl:
		if n.Recv == nil ||
			!n.Name.IsExported() ||
			len(n.Recv.List) != 1 {
			return nil
		}
		t, ok := n.Recv.List[0].Type.(*ast.StarExpr)
		if !ok {
			return nil
		}
		if t.X.(*ast.Ident).String() != "SugaredLogger" {
			return nil
		}
		log.Printf("func name: %s", n.Name.String())
		v.funcs = append(v.funcs, rewriteFunc(n))
	}
	return v
}

func walkAst(node ast.Node) ([]ast.Decl, error) {
	v := &visitor{}
	ast.Walk(v, node)
	log.Printf("funcs len: %d", len(v.funcs))
	var decls []ast.Decl
	for _, v := range v.funcs {
		decls = append(decls, v)
	}
	return decls, nil
}

func rewriteFunc(fn *ast.FuncDecl) *ast.FuncDecl {
	fn.Recv = nil
	fnName := fn.Name.String()
	var args []string
	for _, field := range fn.Type.Params.List {
		for _, id := range field.Names {
			idStr := id.String()
			_, ok := field.Type.(*ast.Ellipsis)
			if ok {
				// Ellipsis args
				idStr += "..."
			}
			args = append(args, idStr)
		}
	}
	exprStr := fmt.Sprintf(`_globalS.%s(%s)`, fnName, strings.Join(args, ","))
	expr, err := parser.ParseExpr(exprStr)
	if err != nil {
		panic(err)
	}
	var body []ast.Stmt
	if fn.Type.Results != nil {
		body = []ast.Stmt{
			&ast.ReturnStmt{
				// Return:
				Results: []ast.Expr{expr},
			},
		}
	} else {
		body = []ast.Stmt{
			&ast.ExprStmt{
				X: expr,
			},
		}
	}
	fn.Body.List = body
	return fn
}

func astToGo(dst *bytes.Buffer, node interface{}) error {
	addNewline := func() {
		err := dst.WriteByte('\n') // add newline
		if err != nil {
			log.Panicln(err)
		}
	}
	addNewline()
	err := format.Node(dst, token.NewFileSet(), node)
	if err != nil {
		return err
	}
	addNewline()
	return nil
}

// Output Go code
func writeGoFile(wr io.Writer, funcs []ast.Decl) error {
	header := `// Code generated by log-gen. DO NOT EDIT.
package logx
`
	buffer := bytes.NewBufferString(header)
	for _, fn := range funcs {
		err := astToGo(buffer, fn)
		if err != nil {
			return errx.WithStackOnce(err)
		}
	}
	_, err := wr.Write(buffer.Bytes())
	return err
}